[build]
  command = "cp .env.example .env && composer install && php artisan key:generate && php artisan migrate --force && npm install && npm run prod"
  publish = "public"

[context.production.environment]
  PHP_VERSION = "8.2"
  APP_KEY = "base64:YourGeneratedAppKey" # Замените на ваш сгенерированный ключ
  DB_CONNECTION = "mysql"
  DB_HOST = "127.0.0.1"
  DB_PORT = "3306"
  DB_DATABASE = "transport_company"
  DB_USERNAME = "kislotnick"
  DB_PASSWORD = "ne489177"

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200
