[build]
  command = "composer install && php artisan key:generate && php artisan migrate --force && npm install && npm run prod"
  publish = "public"

[context.production.environment]
  PHP_VERSION = "8.2"

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200
